package com.nsh.dtq.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nsh.dtq.entity.ChoiceQuestion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHOICE_QUESTION".
*/
public class ChoiceQuestionDao extends AbstractDao<ChoiceQuestion, Long> {

    public static final String TABLENAME = "CHOICE_QUESTION";

    /**
     * Properties of entity ChoiceQuestion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question = new Property(1, String.class, "question", false, "QUESTION");
        public final static Property AnswerA = new Property(2, String.class, "answerA", false, "ANSWER_A");
        public final static Property AnswerB = new Property(3, String.class, "answerB", false, "ANSWER_B");
        public final static Property AnswerC = new Property(4, String.class, "answerC", false, "ANSWER_C");
        public final static Property AnswerD = new Property(5, String.class, "answerD", false, "ANSWER_D");
    }


    public ChoiceQuestionDao(DaoConfig config) {
        super(config);
    }
    
    public ChoiceQuestionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHOICE_QUESTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"QUESTION\" TEXT," + // 1: question
                "\"ANSWER_A\" TEXT," + // 2: answerA
                "\"ANSWER_B\" TEXT," + // 3: answerB
                "\"ANSWER_C\" TEXT," + // 4: answerC
                "\"ANSWER_D\" TEXT);"); // 5: answerD
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHOICE_QUESTION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChoiceQuestion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String question = entity.getQuestion();
        if (question != null) {
            stmt.bindString(2, question);
        }
 
        String answerA = entity.getAnswerA();
        if (answerA != null) {
            stmt.bindString(3, answerA);
        }
 
        String answerB = entity.getAnswerB();
        if (answerB != null) {
            stmt.bindString(4, answerB);
        }
 
        String answerC = entity.getAnswerC();
        if (answerC != null) {
            stmt.bindString(5, answerC);
        }
 
        String answerD = entity.getAnswerD();
        if (answerD != null) {
            stmt.bindString(6, answerD);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChoiceQuestion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String question = entity.getQuestion();
        if (question != null) {
            stmt.bindString(2, question);
        }
 
        String answerA = entity.getAnswerA();
        if (answerA != null) {
            stmt.bindString(3, answerA);
        }
 
        String answerB = entity.getAnswerB();
        if (answerB != null) {
            stmt.bindString(4, answerB);
        }
 
        String answerC = entity.getAnswerC();
        if (answerC != null) {
            stmt.bindString(5, answerC);
        }
 
        String answerD = entity.getAnswerD();
        if (answerD != null) {
            stmt.bindString(6, answerD);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChoiceQuestion readEntity(Cursor cursor, int offset) {
        ChoiceQuestion entity = new ChoiceQuestion( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // question
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // answerA
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // answerB
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // answerC
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // answerD
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChoiceQuestion entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAnswerA(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAnswerB(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAnswerC(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAnswerD(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChoiceQuestion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChoiceQuestion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChoiceQuestion entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
