package com.nsh.dtq.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nsh.dtq.entity.ChoiceQuestion;

import com.nsh.dtq.db.ChoiceQuestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig choiceQuestionDaoConfig;

    private final ChoiceQuestionDao choiceQuestionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        choiceQuestionDaoConfig = daoConfigMap.get(ChoiceQuestionDao.class).clone();
        choiceQuestionDaoConfig.initIdentityScope(type);

        choiceQuestionDao = new ChoiceQuestionDao(choiceQuestionDaoConfig, this);

        registerDao(ChoiceQuestion.class, choiceQuestionDao);
    }
    
    public void clear() {
        choiceQuestionDaoConfig.clearIdentityScope();
    }

    public ChoiceQuestionDao getChoiceQuestionDao() {
        return choiceQuestionDao;
    }

}
